# Dependencies
markdown:         kramdown
gems:             [jekyll-paginate,jekyll-gist,pygments.rb]
highlighter:      rouge

google_analytics: UA-80451970-1
# Permalinks
permalink:        :title

# Setup
title:            "Matteo D'Achille"
tagline:          "PhD Candidate"
description:      "PhD candidate at <br/>- CEA Saclay<br/>- Coll√®ge de France <br/> - UVSQ"
url:              https://matteodachille.github.io/
baseurl:          https://matteodachille.github.io/
tag_page: 		  tags
categories_page:	categories
name:             "Matteo D'Achille"
author:           "Matteo D'Achille"
github:			  matteodachille
linkedin:         matteopdachille
researchgate:     "Matteo_Dachille"
academia:         "MatteoDAchille"
mendeley:         "matteo-dachille"
twitter:          
email:			"matteopietro.dachille@studenti.unimi.it"

paginate:         2

excerpt_separator: '<!--more-->'

# Custom vars
version:          0.9.9

repository:       https://github.com/matteodachille/matteodachille.github.io
